# set up the default terminal
ENV["TERM"]="linux"

# set minimum version for Vagrant
Vagrant.require_version ">= 2.2.10"
Vagrant.configure("2") do |config|
  config.vm.define "techtrends" do |techtrends|
    techtrends.vm.hostname = "techtrends"
    techtrends.vm.provision "shell",
    inline: "sudo su - && zypper update && zypper install -y apparmor-parser"
    
    # Set the image for the vagrant box
    # techtrends.vm.box = "opensuse/Leap-15.4.x86_64"
    techtrends.vm.box = "opensuse/Leap-15.2.x86_64"
    # Set the image version
    # techtrends.vm.box_version = "15.4.6.153"
    techtrends.vm.box_version = "15.2.31.632"
    
    # Forward the ports from the guest VM to the local host machine
    # Forward more ports, as needed
    techtrends.vm.network "forwarded_port", guest: 8080, host: 8080
    techtrends.vm.network "forwarded_port", guest: 6111, host: 6111
    techtrends.vm.network "forwarded_port", guest: 6112, host: 6112
    techtrends.vm.network "forwarded_port", guest: 30007, host: 30007
    techtrends.vm.network "forwarded_port", guest: 30008, host: 30008
    
    # Set the static IP for the vagrant box
    techtrends.vm.network "private_network", ip: "192.168.10.11"
    
    if Vagrant.has_plugin?("vagrant-proxyconf")
      techtrends.proxy.http = "http://192.168.56.1:3128"
      techtrends.proxy.https = "http://192.168.56.1:3128"
      techtrends.proxy.no_proxy = "localhost,127.0.0.1"
    end
    
    # Configure the parameters for VirtualBox provider
    techtrends.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
end