apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: mivodu/techtrends:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        resources: 
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - containerPort: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
